---
- name: Qtree server Setup
  become: yes
  hosts: servergroup
  tasks:
    - name: Create an application user
      user:
        name: wipro
        password: test123
    - name: Create application file
      file:
        path: /root/sample.html
        state: touch    